[build]
  command = "npm run build"
  publish = "public"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
